# Author: Simon Blanke
# Email: simon.blanke@yahoo.com
# License: MIT License
os:
  - linux

language: python

python:
  - "3.7"

install:
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install scikit-learn
  - pip install xgboost
  - pip install lightgbm
  - pip install catboost
  - pip install tensorflow
  - pip install keras
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install .

script:
  - pytest --cov=hyperactive/

after_success:
  - coveralls
